ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'REMOVE_FROM_CART';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CART_VIEWED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CHECKOUT_STARTED';
ALTER TYPE "AnalyticsEventType" ADD VALUE IF NOT EXISTS 'CHECKOUT_INFO_COMPLETED';
