import { defineArrayMember, defineField, defineType } from "sanity";

export const homePageSchema = defineType({
  name: "homePage",
  title: "Pagina de inicio",
  type: "document",
  groups: [
    { name: "content", title: "Contenido", default: true },
    { name: "featured", title: "Destacados" },
    { name: "promo", title: "Promocion" },
    { name: "institutional", title: "Institucional" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Nombre interno",
      description: "Solo para identificar este documento dentro del Studio.",
      type: "string",
      group: "content",
      initialValue: "Pagina de inicio",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTitle",
      title: "Titulo principal",
      description: "Titulo destacado que puede mostrarse en la portada.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroImage",
      title: "Imagen principal",
      description: "Imagen destacada para el bloque principal de la portada.",
      type: "imageWithAlt",
      group: "content",
    }),
    defineField({
      name: "heroText",
      title: "Texto principal",
      description: "Texto breve de apoyo para la portada.",
      type: "text",
      group: "content",
      rows: 3,
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Texto del boton principal",
      description: "Texto del llamado a la accion del hero.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroCtaHref",
      title: "Link del boton principal",
      description: "URL del llamado a la accion del hero.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroSlides",
      title: "Slides del hero",
      description: "Banners principales del hero de la portada.",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "homeHeroSlide" })],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: "featuredCategories",
      title: "Categorias destacadas",
      description: "Selecciona categorias para destacar en la portada.",
      type: "array",
      group: "featured",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "category" }],
        }),
      ],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "featuredProducts",
      title: "Productos destacados",
      description: "Selecciona productos para destacar en la pagina de inicio.",
      type: "array",
      group: "featured",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "product" }],
        }),
      ],
    }),
    defineField({
      name: "promoTitle",
      title: "Titulo promocional",
      description: "Titulo breve para el bloque promocional de la home.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "promoText",
      title: "Texto promocional",
      description: "Mensaje principal del bloque promocional.",
      type: "text",
      group: "promo",
      rows: 3,
    }),
    defineField({
      name: "promoCtaLabel",
      title: "Texto del boton promocional",
      description: "Llamado a la accion del bloque promocional.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "promoCtaHref",
      title: "Link del boton promocional",
      description: "URL del bloque promocional.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "institutionalTitle",
      title: "Titulo institucional",
      description: "Titulo para la seccion institucional de la portada.",
      type: "string",
      group: "institutional",
    }),
    defineField({
      name: "institutionalText",
      title: "Texto institucional",
      description: "Texto breve para contar la propuesta de la marca.",
      type: "text",
      group: "institutional",
      rows: 4,
    }),
    defineField({
      name: "seo",
      title: "SEO",
      description: "Configuracion SEO especifica para la pagina de inicio.",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "heroTitle",
    },
  },
});
