import { defineArrayMember, defineField, defineType } from "sanity";

export const homePageSchema = defineType({
  name: "homePage",
  title: "Página de inicio",
  type: "document",
  groups: [
    { name: "content", title: "Contenido", default: true },
    { name: "featured", title: "Destacados" },
    { name: "promo", title: "Promoción" },
    { name: "institutional", title: "Institucional" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Nombre interno",
      description: "Solo para identificar este documento dentro del estudio.",
      type: "string",
      group: "content",
      initialValue: "Página de inicio",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroTitle",
      title: "Título principal",
      description: "Título destacado que puede mostrarse en la portada.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroImage",
      title: "Imagen principal",
      description: "Imagen destacada para el bloque principal de la portada.",
      type: "imageWithAlt",
      group: "content",
    }),
    defineField({
      name: "heroText",
      title: "Texto principal",
      description: "Texto breve de apoyo para la portada.",
      type: "text",
      group: "content",
      rows: 3,
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Texto del botón principal",
      description: "Texto del llamado a la acción del bloque principal.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroCtaHref",
      title: "Enlace del botón principal",
      description: "URL del llamado a la acción del bloque principal.",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "heroSlides",
      title: "Diapositivas principales",
      description: "Banners principales de la portada.",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "homeHeroSlide" })],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: "featuredCategories",
      title: "Categorías destacadas",
      description: "Seleccioná categorías para destacar en la portada.",
      type: "array",
      group: "featured",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "category" }],
        }),
      ],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "featuredProducts",
      title: "Productos destacados",
      description: "Seleccioná productos para destacar en la página de inicio.",
      type: "array",
      group: "featured",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "product" }],
        }),
      ],
    }),
    defineField({
      name: "campaignFeaturedTitle",
      title: "Título de la campaña destacada",
      description: "Título para la nueva sección con banner y productos curados.",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "campaignFeaturedText",
      title: "Texto de la campaña destacada",
      description: "Texto breve de apoyo para la selección manual de productos.",
      type: "text",
      group: "featured",
      rows: 3,
    }),
    defineField({
      name: "campaignFeaturedCtaLabel",
      title: "Texto del enlace de la campaña",
      description: "Etiqueta opcional para enlazar la selección.",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "campaignFeaturedCtaHref",
      title: "Enlace de la campaña",
      description: "URL opcional para complementar la sección destacada.",
      type: "string",
      group: "featured",
    }),
    defineField({
      name: "campaignFeaturedProducts",
      title: "Productos de la campaña",
      description: "Selección manual de productos para combos especiales, fechas festivas o curaduría del cliente.",
      type: "array",
      group: "featured",
      of: [
        defineArrayMember({
          type: "reference",
          to: [{ type: "product" }],
        }),
      ],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: "spotlightProduct",
      title: "Producto destacado principal",
      description: "Producto protagonista para la sección editorial principal de la portada.",
      type: "reference",
      group: "featured",
      to: [{ type: "product" }],
    }),
    defineField({
      name: "promoTitle",
      title: "Título promocional",
      description: "Título breve para el bloque promocional de la portada.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "promoText",
      title: "Texto promocional",
      description: "Mensaje principal del bloque promocional.",
      type: "text",
      group: "promo",
      rows: 3,
    }),
    defineField({
      name: "promoCtaLabel",
      title: "Texto del botón promocional",
      description: "Llamado a la acción del bloque promocional.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "promoCtaHref",
      title: "Enlace del botón promocional",
      description: "URL del bloque promocional.",
      type: "string",
      group: "promo",
    }),
    defineField({
      name: "institutionalTitle",
      title: "Título institucional",
      description: "Título para la sección institucional de la portada.",
      type: "string",
      group: "institutional",
    }),
    defineField({
      name: "institutionalText",
      title: "Texto institucional",
      description: "Texto breve para contar la propuesta de la marca.",
      type: "text",
      group: "institutional",
      rows: 4,
    }),
    defineField({
      name: "seo",
      title: "SEO",
      description: "Configuración SEO específica para la página de inicio.",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "heroTitle",
    },
  },
});
